version: "3.4"
services:
    front:
        image: dock.grazy.ovh/demo-front:latest
        ports:
            - "3000:3000"
        environment:
            BACKURL: http://back:3001/

    back:
        image: dock.grazy.ovh/demo-back:latest
        volumes:
            - backdata:/app/data
volumes:
    backdata:
        driver: local
        driver_opts:
            device: //192.168.0.100/home
            o: username=test,password=motdepasse,uid=1000,gid=1000